# https://www.iana.org/assignments/media-types/media-types.xhtml
terms:
- id: "application/pdf"
  term: "application/pdf"
- id: "application/x-shockwave-flash"
  term: "application/x-shockwave-flash"
- id: "audio/mp4"
  term: "audio/mp4"
- id: "audio/mpeg"
  term: "audio/mpeg"
- id: "audio/ogg"
  term: "audio/ogg"
- id: "audio/vnd.rn-realaudio"
  term: "audio/vnd.rn-realaudio"
- id: "audio/vnd.wav"
  term: "audio/vnd.wav"
- id: "audio/webm"
  term: "audio/webm"
- id: "audio/x-aac"
  term: "audio/x-aac"
- id: "audio/x-caf"
  term: "audio/x-caf"
- id: "image/bmp"
  term: "image/bmp"
- id: "image/gif"
  term: "image/gif"
- id: "image/ico"
  term: "image/ico"
- id: "image/jpeg"
  term: "image/jpeg"
- id: "image/png"
  term: "image/png"
- id: "image/svg+xml"
  term: "image/svg+xml"
- id: "image/tiff"
  term: "image/tiff"
- id: "text/plain"
  term: "text/plain"
- id: "video/avi"
  term: "video/avi"
- id: "video/mpeg"
  term: "video/mpeg"
- id: "video/mp4"
  term: "video/mp4"
- id: "video/ogg"
  term: "video/ogg"
- id: "video/quicktime"
  term: "video/quicktime"
- id: "video/webm"
  term: "video/webm"
- id: "video/x-matroska"
  term: "videox-/matroska"
- id: "video/x-ms-wmv"
  term: "video/x-ms-wmv"
- id: "video/x-flv"
  term: "video/x-flv"
