# https://www.iana.org/assignments/media-types/media-types.xhtml
# https://www.htmlquick.com/reference/mime-types.html
terms:
- id: "application/pdf"
  term: "application/pdf"
  active: true
- id: "application/x-shockwave-flash"
  term: "application/x-shockwave-flash"
  active: true
- id: "audio/mp4"
  term: "audio/mp4"
  active: true
- id: "audio/mpeg"
  term: "audio/mpeg"
  active: true
- id: "audio/ogg"
  term: "audio/ogg"
  active: true
- id: "audio/vnd.rn-realaudio"
  term: "audio/vnd.rn-realaudio"
  active: true
- id: "audio/vnd.wav"
  term: "audio/vnd.wav"
  active: true
- id: "audio/webm"
  term: "audio/webm"
  active: true
- id: "audio/x-aac"
  term: "audio/x-aac"
  active: true
- id: "audio/x-caf"
  term: "audio/x-caf"
  active: true
- id: "image/bmp"
  term: "image/bmp"
  active: true
- id: "image/gif"
  term: "image/gif"
  active: true
- id: "image/ico"
  term: "image/ico"
  active: true
- id: "image/jpeg"
  term: "image/jpeg"
  active: true
- id: "image/png"
  term: "image/png"
  active: true
- id: "image/svg+xml"
  term: "image/svg+xml"
  active: true
- id: "image/tiff"
  term: "image/tiff"
  active: true
- id: "text/plain"
  term: "text/plain"
  active: true
- id: "video/avi"
  term: "video/avi"
  active: true
- id: "video/mpeg"
  term: "video/mpeg"
  active: true
- id: "video/mp4"
  term: "video/mp4"
  active: true
- id: "video/ogg"
  term: "video/ogg"
  active: true
- id: "video/quicktime"
  term: "video/quicktime"
  active: true
- id: "video/webm"
  term: "video/webm"
  active: true
- id: "video/x-matroska"
  term: "videox-/matroska"
  active: true
- id: "video/x-ms-wmv"
  term: "video/x-ms-wmv"
  active: true
- id: "video/x-flv"
  term: "video/x-flv"
  active: true
