development:
  adapter: redis
  url: redis://localhost:6379/1
test:
  #adapter: async
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: my_app_production
