default: &default
  user: <%= ENV['FCREPO_USERNAME'] %>
  password: <%= ENV['FCREPO_PASSWORD'] %>
  url: http://<%= ENV['FCREPO_HOST'] %>:<%= ENV['FCREPO_PORT'] || 8984 %><%= ENV['FCREPO_PATH']%>
  base_path: <%= ENV['FCREPO_BASE_PATH'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
