development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8080/fcrepo/rest
  #url: http://127.0.0.1:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest
  base_path: /hyrax-development
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8080/fcrepo/rest
  #url: http://127.0.0.1:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest
  base_path: /hyrax-development
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8080/fcrepo/rest
  #url: http://127.0.0.1:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest
  base_path: /hyrax-development
