# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2dcdb876447ae103a6ff24c4c42f87e8906e65b956c3ff2d14025dd7079c5ad579adf6f5b203a3b25d3e306e6666e32cd1f49e49ad3e2fa840bd1ebe28233b7e

test:
  secret_key_base: 1e5ef4076ec252364e08ab6a6e96e49d5f60fc484c794205cf52b6260e4e5b1ad2ca2d96b09bb78ecbc594a9170dfc19c367bb71ffbdbe66aa23a7a4e5fbed84

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
